### ISSUE TITLE
Not working in Elementary OS (based on Ubuntu Bionic)

### ISSUE THREAD

**Issue by da0ist** [Tookmund/Swapspace#26]
![image](https://user-images.githubusercontent.com/7945846/92291282-cd1a1880-eecc-11ea-8a87-a4473d4e87bd.png)

**Comment by Tookmund** [comment]
What version of swapspace are your running?

Could you stop the service and run swapspace in a terminal:

swapspace -v | tee swapspace.log 

And attach the resulting swapspace.log to this bug report once it returns to the state you screenshotted. 

For the future, I recommend installing swapspace.service instead of swapspace.lsbinit since you’re using systemd. 

My current theory is that swapspace could be having trouble allocating new swapfiles and errors might not be logged correctly because the lsb init script daemonizes the program. 

Jacob

**Comment by da0ist** [comment]
I do "sudo apt install swapspace". How do I specify service?

**Comment by Tookmund** [comment]
Ah you don't have the systemd service installed because Ubuntu Bionic has a version of swapspace (1.10) that is about 14 years old. Could you please run `swapspace -V` to confirm this?

Because the version you have is so old, you might be running into the /dev/shm issue fixed in 2014 with version 1.11.
(https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=691128)
Could you also run `df -h /dev/shm` and attach the output?

In a more concise form, here's all the commands I'd like you to run to help me debug this issue. 
Please attach the output of all of them.
```
# Check your version of swapspace
swapspace -V

# check the memory allocated to /dev/shm
df -h /dev/shm

# stop the service
sudo systemctl stop swapspace

# run swapspace in verbose mode, with output both to the terminal and to swapspace.log
# Please run this until the situation you pictured above appears again, if possible
sudo swapspace -v | tee swapspace.log
```

**Comment by da0ist** [comment]
jeward@bionic:/var/log$ swapspace -V
swapspace 1.10-4, Wed, 17 Sep 2008

Copyright (c) 2004-2005 Software Industry Promotion Agency of Thailand
Written by Jeroen T. Vermeulen <jtv@sipa.or.th>
This program is free software, and is available for use under the GNU
General Public License (GPL).

jeward@bionic:/var/log$ df -h /dev/shm
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           868M  391M  478M  45% /dev/shm

![image](https://user-images.githubusercontent.com/7945846/92576874-deea1b80-f23e-11ea-8356-f8ba6b687e24.png)

**Comment by da0ist** [comment]
It doesn't log anywhere that I can find. I'm assuming you'll advise me to compile from source, so I'll try that now.

**Comment by da0ist** [comment]
Looks like the current version works!

![image](https://user-images.githubusercontent.com/7945846/92578896-5caf2680-f241-11ea-87a4-6ba3d8cf31e1.png)

**Comment by Tookmund** [comment]
Based on that df output, you've definitely run into the /dev/shm bug so any version 1.11 or above should work. Glad it was just that. 

That you're not seeing any log output is very strange. I'll have to take a look at the changes between 1.10 and now because swapspace should be very verbose with the -v flag.
