### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by Raj2032** [Tookmund/Swapspace#37]
Hi, I wanted to know if this is still being maintained or not?

**Comment by Tookmund** [comment]
As you can probably tell from the commit history over the past several years, I have not had much time to work on this project. I certainly wouldn't describe it as well maintained at the moment, though I would still like to get 1.18 out before the end of the year (which is fairly ridiculous I realize, given that the PR it contains has been open since December of last year)

**Comment by Raj2032** [comment]
Fair enough mate, I understand and yep hopefully it does get released :)
------- Original Message -------
